### ISSUE TITLE
Test 'all_tests.py' fails

### ISSUE THREAD

**Issue by labrys** [SickRage/old-sickrage-issues#2] opened 2015-11-15 22:07 UTC
##### Configuration:
- Commits: 
  - Master sickrage/sickrage@deeed2b20651becabe2e04346deb7404dd2e40a8 
  - Dev sickrage/sickrage@16faf4c9368d25c3484ff105b654fc61baa04a54
- OS: Win 10 x64, Win 8.1 x64, Win 7 x64, Win XP x86
- Python: 2.7.10 x86
##### Steps to reproduce:
1. Clean install of SickRage
2. SickRage is not running (and not running as a daemon)
3. Run `tests/all_tests.py` from the command line
##### Results:
- two tests fail: `pp_tests` and `scene_helpers_tests`
##### Expectations:

None of the tests should fail.
##### Logs:

(from Win 10 x64)
[master branch log](https://gist.github.com/labrys/fde5d650e30499764bce)
[develop branch log](https://gist.github.com/labrys/0636587e6e3e4d596ab0)

**Comment by labrys** [comment] 2015-11-15 22:10
Running `pp_tests` and `scene_helpers_tests` individually fails as well.

**Comment by miigotu** [comment] 2015-11-16 03:08
Not quite sure what this could be, they both work on linux...

**Comment by labrys** [comment] 2015-11-16 03:56
Yeah it looks like its a windows thing.  Haven't really looked into it yet, just noticed it while running the tests prior to pushing the status strings fix.

**Comment by WebSpider** [comment] 2015-11-16 06:59
Ah, here all are :)
Let me know if the bots need adjusting?
On my way to work now.

**Comment by miigotu** [comment] 2015-11-16 07:49
@WebSpider yes, we need to talk =P Pretty much everything needs changed

**Comment by alisonatwork** [comment] 2015-11-18 07:25
I can confirm this failure still existing on develop under Windows 10. I skipped over it when I added the exceptions_helper_test over the weekend but can give it a look if no one is on it yet :)

**Comment by miigotu** [comment] 2015-11-18 07:49
If you can =P. Dont have windows installed and my lappy just sucks too much for virtualization

**Comment by labrys** [comment] 2015-11-18 07:56
I'm in process installing a clean XP install to test it with a fresh system.  Just waiting on Windows updates.  <Looks at watch> :clock1030: :zzz:

**Comment by alisonatwork** [comment] 2015-11-18 08:56
Awesome. Let me know if you need a hand, I am used to being the sucker who has to make Unix-y things work on Windows, most of colleagues use Linux or Mac and laugh at me, until we compare Steam libraries :wink:

**Comment by labrys** [comment] 2015-11-18 09:33
Lol.  Yeah I run Debian and Windows (XP x86, Vista x86 and x64, 7 x64, 8.1 x64, 10 x64) myself.  Every time I try to ditch Windows something comes up that delays it.

**Comment by labrys** [comment] 2015-11-18 09:41
Still updating :frowning: :zzz:

**Comment by miigotu** [comment] 2015-11-18 09:43
@labrys you dont even need updates to test or run SR btw =P

**Comment by labrys** [comment] 2015-11-18 09:44
I know.  The system is going to be a production PC, not just building for the test, so it needs the updates.

**Comment by labrys** [comment] 2015-11-18 11:48
XP updates finished (finally).  Still get the `pp_tests.PPBasicTests` failure:

```
======================================================================
ERROR: test_process (pp_tests.PPBasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Src\sick.dev\tests\pp_tests.py", line 63, in test_process
    self.assertTrue(pp.process())
  File "C:\Src\sick.dev\sickbeard\postProcessor.py", line 1060, in process
    raise EpisodePostProcessingFailedException("File is locked for reading/writi
ng")
EpisodePostProcessingFailedException: File is locked for reading/writing

======================================================================
ERROR: test_process (pp_tests.PPBasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Src\sick.dev\tests\test_lib.py", line 137, in tearDown
    tearDown_test_episode_file()
  File "C:\Src\sick.dev\tests\test_lib.py", line 227, in tearDown_test_episode_f
ile
    shutil.rmtree(FILEDIR)
  File "c:\Python\Python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "c:\Python\Python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: u'C:\\Src\\sick.dev\\tests\\show name\\show name - s04e
02.mkv'

----------------------------------------------------------------------
Ran 68 tests in 67.844s

FAILED (errors=2, expected failures=1)
E
======================================================================
ERROR: testAll (__main__.AllTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "all_tests.py", line 49, in testAll
    sys.exit(-1)
SystemExit: -1

----------------------------------------------------------------------
Ran 1 test in 94.188s

FAILED (errors=1)
```

Going to look into it some more and see what I can find.

**Comment by labrys** [comment] 2015-11-18 11:50
A second run and I get the `scene_helpers_tests` errors now too.

**Comment by labrys** [comment] 2015-11-22 11:04
Haven't had a chance to get back to this lately... still on my plate though..

**Comment by labrys** [comment] 2015-11-23 18:06
Started digging into this, but haven't gotten very far with it yet.  My suspicion is that its not an issue with SickRage but with the test files created during the test.

**Comment by miigotu** [comment] 2015-11-24 01:21
I think it is more the order the tests are run is different on windows. The order matters or it doesnt work, because some files created by one test are used by other tests.

**Comment by labrys** [comment] 2015-11-25 13:51
As this appears to be affect Windows only and does not appear to affect the actual operation, I'm going to close this issue.  It can be readdressed as we improve and rewrite the tests.

**Comment by alisonatwork** [comment] 2015-11-25 21:34
This decision is a little unfortunate, because the new test structure committed in https://github.com/SickRage/SickRage/commit/12191d14e203f959fd22cab00285f28c96b546d9 breaks all_tests.py completely on Windows, which feels like a step backwards to me.

**Comment by labrys** [comment] 2015-11-25 21:39
@alisonatwork I'm not forgetting about it, just the whole testing suite needs rewriting.  We are barely scratching the surface of what needs to be tested so fixing this when the whole thing needs reworked is a waste of effort in my opinion.  If you feel an interim fix is important enough we can reopen the issue.  Thoughts?

**Comment by MGaetan89** [comment] 2015-11-25 21:43
@alisonatwork I agree we should work on making the tests pass even if we are rewriting that part and adding new tests.
I think I broke the tests on Windows because of [this new line](https://github.com/SickRage/SickRage/commit/12191d14e203f959fd22cab00285f28c96b546d9#diff-38840560f64fc557290d9e567763ed4fR57), as Windows uses `\` and not `/` for directory separator.
I don't have any Windows machine to try to fix this. But feel free to do it if you are willing to do so.
I will see if it is possible to configure Travis to run tests on different OS (Windows/Linux at least) so we can prevent such issues in the future.

**Comment by labrys** [comment] 2015-11-25 21:46
@MGaetan89 Travis does not... appVeyor that we are looking to add does...

**Comment by alisonatwork** [comment] 2015-11-25 21:46
No, it's fine, I understand that CI is running on Linux and I imagine most of the end users are running Linux too. For me I am only jumping in to develop occasionally, so it is frustrating when I can't get a clean build or a running system on the develop branch and I tend to give up before I get started, but honestly it's more important that the regular contributors are able to maximize their velocity, so you are right, it's not worth worrying about right now :sunglasses:

**Comment by labrys** [comment] 2015-11-25 21:47
It is worth working on but chasing this down when the logic behind the test is flawed, seems like  the wrong way to approach it.

**Comment by alisonatwork** [comment] 2015-11-25 21:49
And @MGaetan89 you are a superstar pythonista! If you replace '/' with os.sep then the tests run again on Windows (and fail how they originally used to, which at least is not a regression). I am a Java guy by trade so this is all new to me :)

**Comment by labrys** [comment] 2015-11-25 21:50
Rewriting the tests in my opinion is probably our highest priority aside from fixing user issues as they arise.  I knew @MGaetan89 was working on tests so I delayed my rewriting while waiting on his new stuff.  As an example our current library test was only generating a single test episode for a single show.

**Comment by MGaetan89** [comment] 2015-11-25 21:55
@alisonatwork I'm kind of learning Python as I work on SickRage ;) Thanks for testing this. If you want to submit a PR to fix it, I will merge it.
@labrys I started cleaning and updating the code a few month back, but without any tests. Considering the increasing number of issues in the previous repository, I decided to add tests while updating the code. Even if they don't cover every use cases, it may (and already did) prevent some issues in the future. If you want to add new tests, you are more than welcome to do it. There is enough work for that I guess :P

**Comment by alisonatwork** [comment] 2015-11-25 21:56
More tests is always good :sunglasses:  Opened the PR @ 198

**Comment by labrys** [comment] 2015-11-25 21:57
Hehe.. I'm a troubleshooter by tried so extensive testing and effective documentation for me is like poetry :)

**Comment by MGaetan89** [comment] 2015-11-25 21:58
@alisonatwork Merged it. Thanks for the fix. It seems to be working on Linux too according to Travis.

**Comment by labrys** [comment] 2015-11-25 22:05
I'll start working on this as soon as I do that rename for @MGaetan89

**Comment by alisonatwork** [comment] 2015-11-25 22:30
OK on a side note, I have looked into the ```feedparser_tests.py``` and these actually fail independently on Windows. The error coming back from feedparser is ```sequence item 0: expected string, dict found```. This can be fixed by changing ```tvcache.py``` or ```rssfeeds.py``` to wrap the request headers dictionary with ```str()```. I am a little worried about changing that unilaterally though, since it may actually be more related to the whole Unicode thing. Might be worth a test by a Linux guy. I'll dig deeper when I have some time, but in this case it feels a bit like an actual bug and not just a quirk of the tests.

The ```scene_helpers_tests``` also fail independently on Windows, so I don't think they are a victim of different test running order either to be honest. But I haven't looked into those ones yet. Will keep in touch as I find time.

**Comment by labrys** [comment] 2015-11-25 22:40
@alisonatwork I agree.  After I work on this one I'll try running the tests individually on Debian if someone doesn't beat me to it.

**Comment by labrys** [comment] 2015-11-25 22:59
@alisonatwork `pp_tests.py` runs individually on Debian with no probs.  `scene_helpers_tests.py` fails the same way on Debian when run individually.

**Comment by alisonatwork** [comment] 2015-11-25 23:05
I probably need to sit down on this a bit longer to work it out. I have a freebsd vm I use for testing UNIX stuff on my work lappy, but either way it sounds like our CI is not failing when the tests fail, which kinda sucks. Got a cold right now and it is late but I'll check back again when I have some time to figure out what's going on if no one else took the ticket before me 😊

**Comment by alisonatwork** [comment] 2015-11-25 23:07
PS did you try feedparser_tests too? I wonder if some of these integration tests fail in different locations/proxies since they are actually querying real life RSS feeds.

**Comment by labrys** [comment] 2015-11-25 23:08
not yet... helping someone t/s a windows issue on irc... try it after though

**Comment by labrys** [comment] 2015-11-25 23:35
`feed-parser_tests.py` worked on debian... aint had a chance to try on windows yet.

**Comment by alisonatwork** [comment] 2015-11-25 23:49
Interesting that that test works for you...

This is a total tangent, but does python have a strict build tool like make/maven/gradle/npm/gulp that can clean, compile and test in a predictable fashion that works on all platforms? Perhaps dirty output dirs is part of the problem like miigo suggested?

This can be avoided with very opinionated build tools, but if devs need to run a bunch of manual commands upfront that CI may (or may not) be automating it can create mysterious test failures. I don't know enough about Python to give good insight here, but can spend some time digging when I get back on a computer (currently on phone).

**Comment by labrys** [comment] 2015-11-25 23:52
imo if everything is built right and used properly, the classes should behave the same cross platform.. if not then the classes need redesigned till they do

**Comment by labrys** [comment] 2015-11-25 23:54
and while there are test suites such as unit tests and nose, and tox to standardize testing its not quite the same thing.

**Comment by labrys** [comment] 2015-11-26 00:00
@alisonatwork you install via the windows installer, correct?

**Comment by alisonatwork** [comment] 2015-11-26 00:14
Yep, i did install via Windows installer on my "server", though I also disabled the service due to NAS/network drive problems we are discussing in the other project.

For development I use Windows 10 with Git 2.x, Python 2.7 and Node 5.x same as I use for my real job. Honestly I'm finding a lot of SickRage tricky to develop without a bunch of secret added dev tools that I guess Linux or Mac guys install separately, so I know I am not really in the mainstream here. I will propose PRs for cross platform support, but if it's not accepted due to making things harder on Linux or Mac, oh well. Those guys contribute a lot more than I do, so the most important thing for the project is that it works well for them so the mainstream (Linux) users can get fixes as quickly as possible.

**Comment by labrys** [comment] 2015-11-26 00:17
I don't do the the node stuff, but my dev setup is Win 10 with git and git extensions.  Python 2.7.10 and 3.4 both are x86 and x64.  I use PyCharm as my IDE.  What dev tools do you need, tbh, its python - a text editor would be sufficient :)

**Comment by labrys** [comment] 2015-11-26 00:19
Oh and I never run the installer, or the service.  Have you had any issues with updating or git commands with the installer?  I'm trying to help someone t/s a windows issue in irc right now.

**Comment by alisonatwork** [comment] 2015-11-26 00:34
Hmm okay, so my production install is on the "server" (I use quotes because it's an alienware alpha that goes to sleep as often as a laptop does - this also causes serious problems with sickrage that I want to look into at some point). That is running Windows 10 and whatever the installer installs, but minus the service because I need access to my NAS so I run it in the foreground same as I used to run SickBears.

All my dev work is done either on my work lappy or my tablet, both of which are Win10 build 10586 with a bunch of dev tools I use for "real" work besides SickRage. Python is not a big deal as long as you run the python.exe explicitly but Node is tricky because the build process forces you to install grunt and bower globally, which conflicts with other projects. I have some workarounds for this, though, so no biggie.

Troubleshooting Windows users (as opposed to devs) from what I've seen the biggest problem is NAS/network drives, which Python handles extremely poorly, and Unicode, which I think we are still struggling with in both develop and master. This is my biggest bugbear since moving to SickRage from SickBeard. SickBeard sucked for torrents but at least it handled strings properly. SickRage is awesome for torrents but sucks for strings. I guess this is worse for anime and East European guys who need their non-Latin characters

**Comment by alisonatwork** [comment] 2015-11-26 00:50
Here is the NAS problem btw. Windows specific but totally unrelated to this ticket: https://github.com/VinceVal/SickRageInstaller/issues/6

**Comment by labrys** [comment] 2015-11-26 01:28
@alisonatwork I'm familiar with that issue too and it fails for me the same way.  As for the `feed-parser_tests.py` they pass here on windows.

**Closed** 2017-12-10 14:40 UTC
Labels: Bug/Issue, Confirmed
