### ISSUE TITLE
Limetorrents search RSS is broken

### ISSUE THREAD

**Issue by fernandog** [SickRage/old-sickrage-issues#437] opened 2016-01-07 15:01 UTC
Its not downloading but I see no messages about ignoring them but instead 
`FINDPROPERS :: Picked *.PROPER.720p.HDTV.x264-2HD[rartv] as the best

also It shouldn't **search** propers for episodes without locations because user may already watched them or when status is archived (ref. 3rd log line bellow)

![image](https://cloud.githubusercontent.com/assets/2620870/12173444/fe68445c-b53d-11e5-892b-be882ea0533e.png)

```
2016-01-07 11:45:53 DEBUG    FINDPROPERS :: Successful match! Result ****.S03E13.REPACK.480p.HDTV.x264-mSD matched to show *
2016-01-07 11:45:53 DEBUG    FINDPROPERS :: Parsed ****.S03E13.REPACK.480p.HDTV.x264-mSD into New Girl - S03E13 [GROUP: mSD] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2016-01-07 11:45:51 DEBUG    FINDPROPERS :: [NZBGeek] :: Search url: https://api.nzbgeek.info/api?apikey=**********&tvdbid=248682&season=5&maxage=3&cat=5030%2C5040&q=****+PROPER%7CREPACK&limit=100&t=tvsearch&offset=0&ep=1
2016-01-07 11:45:48 INFO     FINDPROPERS :: [NZBGeek] :: Searching for any new PROPER releases from NZBGeek
```

**Comment by SickRage2** [comment] 2016-01-07 15:01
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by fernandog** [comment] 2016-01-07 15:29
@miigotu @duramato don't know from there SR got those results:

https://gist.github.com/fernandog/ab398262703e519de920

alpharatio and limetorrents urls must be wrong because using browser I get no results for those URL

also nzbgeek don't have any result for 
https://api.nzbgeek.info/api?apikey=**********&tvdbid=248682&season=5&maxage=3&cat=5030%2C5040&q=New.Girl+PROPER%7CREPACK&limit=100&t=tvsearch&offset=0&ep=1

so from where SR got those results that were picked??

```
FINDPROPERS :: Successful match! Result Mike.and.Molly.S05E09.PROPER.720p.HDTV.x264-2HD[rartv] matched to show Mike & Molly
FINDPROPERS :: Successful match! Result New.Girl.S04E18.REPACK.720p.HDTV.x264-KILLERS[rarbg] matched to show New Girl

**Comment by duramato** [comment] 2016-01-07 15:37
They might have been removed from geek

**Comment by fernandog** [comment] 2016-01-07 15:41
The name in url is wrong isnt? There is a dot instead of space in show name

**Comment by DarkSupremo** [comment] 2016-01-08 18:01
Its constantly downloading few episodes from old seasons from multiple series almost all days... not sure if its proper or what

**Comment by labrys** [comment] 2016-01-08 20:19
Duplicate of #446

**Comment by fernandog** [comment] 2016-01-08 22:18
Its a issue with alpharatio and limetorrents. 
Alpharatio is ok now
Limetorrents still returning wrong results when rss. Normal search return ok

**Comment by fernandog** [comment] 2016-01-18 09:12
@labrys which PR fixes it ?

https://github.com/SickRage/SickRage/commits/develop/sickbeard/providers/limetorrents.py

**Comment by labrys** [comment] 2016-01-18 09:19
@fernandog I was under the impression that it was fixed by @miigotu's provider rewrites.

**Comment by fernandog** [comment] 2016-01-18 09:40
not yet.
I sent a email to lime torrents so they can check if their searchrss is broken.
but lime torrent still need a rewritten to parse site.

**Closed** 2016-11-21 19:05 UTC
Labels: Bug/Issue, Confirmed, Fix Pending
