### ISSUE TITLE
can't update sickrage

### ISSUE THREAD

**Issue by jamaroney** [SickRage/old-sickrage-issues#1493] opened 2017-03-20 13:25 UTC
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 
Master/Commit: 78143873f776c0506c340c0eb6bab2f166952968
OS: FREEBSD 10
What you did: 
What happened: It won't update (manually or automatically)
What you expected:
Logs:
```
2017-03-20 08:55:13 INFO     MAIN :: Backing up database before upgrade
2017-03-20 08:55:13 INFO     MAIN :: Proceeding with upgrade
2017-03-20 08:55:13 INFO     MAIN :: Add minor version numbers to database
2017-03-20 08:55:14 INFO     MAIN :: Updated to: 43.1
2017-03-20 08:55:14 INFO     MAIN :: Backing up database before upgrade
2017-03-20 08:55:14 INFO     MAIN :: Proceeding with upgrade
2017-03-20 08:55:17 INFO     MAIN :: Starting SickRage [] using '/mnt/HDD/extensions/sickrage/config.ini'
2017-03-20 08:55:17 INFO     MAIN :: Generating New API key
2017-03-20 08:55:17 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2017-03-20 08:55:17 INFO     CHECKVERSION :: Checking for updates using SOURCE
2017-03-20 08:55:18 INFO     MAIN :: Checking for scene exception updates from http://sickrage.github.io/scene_exceptions/scene_exceptions.json
2017-03-20 08:55:22 INFO     MAIN :: Checking for XEM scene exception updates for theTVDB
2017-03-20 08:55:31 INFO     MAIN :: Checking for scene exception updates for AniDB
2017-03-20 08:55:43 INFO     Thread-14 :: Checking for updates using SOURCE
2017-03-20 08:56:14 INFO     Thread-17 :: Config backup in progress...
2017-03-20 08:56:14 INFO     Thread-17 :: Config backup successful, updating...
2017-03-20 08:56:41 INFO     Thread-17 :: Creating update folder /mnt/HDD/extensions/sickrage/sr-update before extracting
2017-03-20 08:56:41 INFO     Thread-17 :: Downloading update from http://github.com/SickRage/SickRage/tarball/master
2017-03-20 08:59:36 INFO     Thread-17 :: Extracting file /mnt/HDD/extensions/sickrage/sr-update/sr-update.tar
2017-03-20 08:59:37 ERROR    Thread-17 :: Error while trying to update: ascii : /mnt/HDD/extensions/sickrage/sr-update/SickRage-SickRage-a0317f3/gui/slick/images/network/stöð 2.png : error 92 : error 94 : ordinal not in range(128)
Traceback (most recent call last):
  File "/mnt/HDD/extensions/sickrage/sickbeard/versionChecker.py", line 816, in update
    tar.extractall(sr_update_dir)
  File "/usr/local/lib/python2.7/tarfile.py", line 2081, in extractall
    self.extract(tarinfo, path)
  File "/usr/local/lib/python2.7/tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/local/lib/python2.7/tarfile.py", line 2194, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/local/lib/python2.7/tarfile.py", line 2234, in makefile
    with bltn_open(targetpath, "wb") as target:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 92-93: ordinal not in range(128)
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Aborting all threads
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Saving all shows to the database
2017-03-20 09:03:33 INFO     EVENT-QUEUE :: Saving config file to disk
2017-03-20 09:03:34 INFO     EVENT-QUEUE :: Shutting down Tornado
2017-03-20 09:03:34 INFO     EVENT-QUEUE :: Restarting SickRage with ['/usr/local/bin/python2.7', u'/mnt/HDD/extensions/sickrage/SickBeard.py', '--quiet', u'--nolaunch']
2017-03-20 09:03:44 INFO     MAIN :: Restore: restoring cache successful
2017-03-20 09:03:44 WARNING  MAIN :: Restore: Unable to remove the cache/mako directory: error 2 : No such file or directory
2017-03-20 09:03:45 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-20 09:03:45 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2017-03-20 09:03:45 DEBUG    MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
2017-03-20 09:03:45 DEBUG    MAIN :: formatting pattern: %SN - S%0SE%0E -> Show Name - S02E03
2017-03-20 09:03:45 DEBUG    MAIN :: Trying to parse Show Name - S02E03.ext
2017-03-20 09:03:45 DEBUG    MAIN :: Parsed Show Name - S02E03.ext into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-20 09:03:45 DEBUG    MAIN :: The name Show Name - S02E03.ext parsed into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-20 09:03:46 DEBUG    MAIN :: Checking database structure...sickbeard.db
2017-03-20 09:03:46 DEBUG    MAIN :: Database upgrade required: Reset Version
2017-03-20 09:03:46 DEBUG    MAIN :: ResetDBVersion upgrade completed
2017-03-20 09:03:46 DEBUG    MAIN :: Checking database structure...cache.db
2017-03-20 09:03:46 DEBUG    MAIN :: Checking database structure...failed.db
2017-03-20 09:03:46 DEBUG    MAIN :: Checking for shows with tvrage id's, since tvrage is gone
2017-03-20 09:03:46 DEBUG    MAIN :: Checking for archived episodes not qualified
2017-03-20 09:03:46 DEBUG    MAIN :: Retrieving the last check time from the DB
2017-03-20 09:03:46 DEBUG    MAIN :: Loading initial show list
2017-03-20 09:03:46 INFO     MAIN :: Starting SickRage [master] using '/mnt/HDD/extensions/sickrage/config.ini'
2017-03-20 09:03:46 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2017-03-20 09:03:46 DEBUG    CHECKVERSION :: Starting new thread: CHECKVERSION
2017-03-20 09:04:00 DEBUG    CHECKVERSION :: cur_commit = 78143873f776c0506c340c0eb6bab2f166952968, newest_commit = a0317f387e1df4fff138ca9f06abb6f40d7921d7, num_commits_behind = 4
2017-03-20 09:04:00 INFO     CHECKVERSION :: New update found for SickRage, starting auto-updater ...
2017-03-20 09:04:18 DEBUG    CHECKVERSION :: cur_commit = 78143873f776c0506c340c0eb6bab2f166952968, newest_commit = a0317f387e1df4fff138ca9f06abb6f40d7921d7, num_commits_behind = 4
2017-03-20 09:04:21 DEBUG    CHECKVERSION :: We can proceed with the update. New update has same DB version
2017-03-20 09:04:21 DEBUG    CHECKVERSION :: We can proceed with the update. Post-Processor is not running
2017-03-20 09:04:21 DEBUG    CHECKVERSION :: We can proceed with the update. Shows are not being updated
2017-03-20 09:04:21 DEBUG    CHECKVERSION :: Proceeding with auto update
2017-03-20 09:04:21 INFO     CHECKVERSION :: Config backup in progress...
2017-03-20 09:04:25 INFO     CHECKVERSION :: Config backup successful, updating...
2017-03-20 09:04:44 DEBUG    CHECKVERSION :: cur_commit = 78143873f776c0506c340c0eb6bab2f166952968, newest_commit = a0317f387e1df4fff138ca9f06abb6f40d7921d7, num_commits_behind = 4
2017-03-20 09:04:44 INFO     CHECKVERSION :: Clearing out update folder /mnt/HDD/extensions/sickrage/sr-update before extracting
2017-03-20 09:04:45 INFO     CHECKVERSION :: Creating update folder /mnt/HDD/extensions/sickrage/sr-update before extracting
2017-03-20 09:04:45 INFO     CHECKVERSION :: Downloading update from http://github.com/SickRage/SickRage/tarball/master
2017-03-20 09:08:37 INFO     Thread-16 :: Config backup in progress...
2017-03-20 09:08:41 INFO     Thread-16 :: Config backup successful, updating...
2017-03-20 09:08:46 INFO     CHECKVERSION :: Extracting file /mnt/HDD/extensions/sickrage/sr-update/sr-update.tar
2017-03-20 09:08:46 DEBUG    POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2017-03-20 09:08:46 INFO     POSTPROCESSOR :: Auto post processing task for /mnt/NAS/downloads was added to the queue
2017-03-20 09:08:47 ERROR    CHECKVERSION :: [7814387] Error while trying to update: ascii : /mnt/HDD/extensions/sickrage/sr-update/SickRage-SickRage-a0317f3/gui/slick/images/network/stöð 2.png : error 92 : error 94 : ordinal not in range(128)
Traceback (most recent call last):
  File "/mnt/HDD/extensions/sickrage/sickbeard/versionChecker.py", line 816, in update
    tar.extractall(sr_update_dir)
  File "/usr/local/lib/python2.7/tarfile.py", line 2081, in extractall
    self.extract(tarinfo, path)
  File "/usr/local/lib/python2.7/tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/local/lib/python2.7/tarfile.py", line 2194, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/local/lib/python2.7/tarfile.py", line 2234, in makefile
    with bltn_open(targetpath, "wb") as target:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 92-93: ordinal not in range(128)
2017-03-20 09:08:47 DEBUG    CHECKVERSION :: Traceback: Traceback (most recent call last):
  File "/mnt/HDD/extensions/sickrage/sickbeard/versionChecker.py", line 816, in update
    tar.extractall(sr_update_dir)
  File "/usr/local/lib/python2.7/tarfile.py", line 2081, in extractall
    self.extract(tarinfo, path)
  File "/usr/local/lib/python2.7/tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/local/lib/python2.7/tarfile.py", line 2194, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/local/lib/python2.7/tarfile.py", line 2234, in makefile
    with bltn_open(targetpath, "wb") as target:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 92-93: ordinal not in range(128)

2017-03-20 09:08:47 INFO     CHECKVERSION :: Update failed!
2017-03-20 09:08:47 DEBUG    CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
2017-03-20 09:08:51 INFO     POSTPROCESSOR-AUTO :: Beginning auto post processing task: /mnt/NAS/downloads
2017-03-20 09:08:51 DEBUG    POSTPROCESSOR-AUTO :: Processing in folder /mnt/NAS/downloads
2017-03-20 09:08:51 INFO     POSTPROCESSOR-AUTO :: Processing /mnt/NAS/downloads
2017-03-20 09:08:51 DEBUG    POSTPROCESSOR-AUTO :: Processing folder /mnt/NAS/downloads
2017-03-20 09:08:52 DEBUG    POSTPROCESSOR-AUTO :: Parsed american.crime.s03e02.720p.hdtv.hevc.x265.rmteam.mkv into american crime - S03E02 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-20 09:08:53 DEBUG    POSTPROCESSOR-AUTO :: You're trying to post process a video that's already been processed, skipping
2017-03-20 09:08:53 DEBUG    POSTPROCESSOR-AUTO :: Skipping already processed file: american.crime.s03e02.720p.hdtv.hevc.x265.rmteam.mkv
2017-03-20 09:08:53 DEBUG    POSTPROCESSOR-AUTO :: You're trying to post process a video that's already been processed, skipping
2017-03-20 09:08:53 DEBUG    POSTPROCESSOR-AUTO :: Skipping already processed file: The.Walking.Dead.S07E14.720p.HDTV.x265.ShAaNiG.mkv
2017-03-20 09:08:53 DEBUG    POSTPROCESSOR-AUTO :: Skipping already processed file: Last.Week.Tonight.with.John.Oliver.S04E06.720p.WEBRip.2CH.x265.HEVC-PSA.mkv
2017-03-20 09:08:53 DEBUG    POSTPROCESSOR-AUTO :: You're trying to post process a video that's already been processed, skipping
2017-03-20 09:08:53 DEBUG    POSTPROCESSOR-AUTO :: Skipping already processed file: feud.s01e03.720p.hdtv.hevc.x265.rmteam.mkv
2017-03-20 09:08:53 DEBUG    POSTPROCESSOR-AUTO :: You're trying to post process a video that's already been processed, skipping
2017-03-20 09:08:53 DEBUG    POSTPROCESSOR-AUTO :: Skipping already processed file: homeland.s06e09.proper.720p.hdtv.hevc.x265.rmteam.mkv
2017-03-20 09:08:53 DEBUG    POSTPROCESSOR-AUTO :: Processing folder /mnt/NAS/downloads/incomplete
2017-03-20 09:08:53 DEBUG    POSTPROCESSOR-AUTO :: /mnt/NAS/downloads/incomplete : No processable items found in folder
2017-03-20 09:08:53 INFO     POSTPROCESSOR-AUTO :: Successfully processed
2017-03-20 09:08:53 INFO     POSTPROCESSOR-AUTO :: Auto post processing task for /mnt/NAS/downloads completed
2017-03-20 09:09:10 DEBUG    Thread-16 :: cur_commit = 78143873f776c0506c340c0eb6bab2f166952968, newest_commit = a0317f387e1df4fff138ca9f06abb6f40d7921d7, num_commits_behind = 4
2017-03-20 09:09:10 INFO     Thread-16 :: Clearing out update folder /mnt/HDD/extensions/sickrage/sr-update before extracting
2017-03-20 09:09:11 INFO     Thread-16 :: Creating update folder /mnt/HDD/extensions/sickrage/sr-update before extracting
2017-03-20 09:09:11 INFO     Thread-16 :: Downloading update from http://github.com/SickRage/SickRage/tarball/master
2017-03-20 09:12:06 INFO     Thread-16 :: Extracting file /mnt/HDD/extensions/sickrage/sr-update/sr-update.tar
2017-03-20 09:12:07 ERROR    Thread-16 :: [7814387] Error while trying to update: ascii : /mnt/HDD/extensions/sickrage/sr-update/SickRage-SickRage-a0317f3/gui/slick/images/network/stöð 2.png : error 92 : error 94 : ordinal not in range(128)
Traceback (most recent call last):
  File "/mnt/HDD/extensions/sickrage/sickbeard/versionChecker.py", line 816, in update
    tar.extractall(sr_update_dir)
  File "/usr/local/lib/python2.7/tarfile.py", line 2081, in extractall
    self.extract(tarinfo, path)
  File "/usr/local/lib/python2.7/tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/local/lib/python2.7/tarfile.py", line 2194, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/local/lib/python2.7/tarfile.py", line 2234, in makefile
    with bltn_open(targetpath, "wb") as target:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 92-93: ordinal not in range(128)
2017-03-20 09:12:07 DEBUG    Thread-16 :: Traceback: Traceback (most recent call last):
  File "/mnt/HDD/extensions/sickrage/sickbeard/versionChecker.py", line 816, in update
    tar.extractall(sr_update_dir)
  File "/usr/local/lib/python2.7/tarfile.py", line 2081, in extractall
    self.extract(tarinfo, path)
  File "/usr/local/lib/python2.7/tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/local/lib/python2.7/tarfile.py", line 2194, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/local/lib/python2.7/tarfile.py", line 2234, in makefile
    with bltn_open(targetpath, "wb") as target:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 92-93: ordinal not in range(128)

2017-03-20 09:13:46 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2017-03-20 09:13:46 INFO     DAILYSEARCHER :: No new released episodes found ...
2017-03-20 09:13:46 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2017-03-20 09:13:46 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from The Walking Dead
2017-03-20 09:13:46 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from The Americans (2013)
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Better Call Saul
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Comedians in Cars Getting Coffee
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from American Crime
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Fargo
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Game of Thrones
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Homeland
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Law & Order: Special Victims Unit
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from The Leftovers
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from The Man in the High Castle
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from The Knick
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Veep
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Full Frontal with Samantha Bee
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from The Big Bang Theory
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/S09E19.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/S09E20.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/S09E21.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/S09E22.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/S09E23.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/S09E24.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/The Big Bang Theory - S10E06.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/The Big Bang Theory - S10E07.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/The Big Bang Theory - S10E08.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/The Big Bang Theory - S10E09.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/The Big Bang Theory - S10E10.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/The Big Bang Theory - S10E11.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/The Big Bang Theory - S10E12.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/The Big Bang Theory - S10E13.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/The Big Bang Theory - S10E14.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/The Big Bang Theory - S10E15.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/The Big Bang Theory - S10E16.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/The Big Bang Theory - S10E17.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Setter sets location to /mnt/NAS/PBO/Video/TV/Big Bang Theory/The Big Bang Theory - S10E18.mp4
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Last Week Tonight with John Oliver
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Westworld
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from 24: Legacy
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from The Good Fight
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from FEUD
2017-03-20 09:13:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Search Mode: RSS
2017-03-20 09:13:57 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: GET URL: https://thepiratebay.org/browse/208/0/4/0 [Status: 200]
2017-03-20 09:14:04 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: GET URL: https://thepiratebay.org/browse/205/0/4/0 [Status: 200]
2017-03-20 09:14:07 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Unable to match Southpark.-.S08E07.-.Goobacks.(Xvid) to a show in your database. Parser result: Southpark - S08E07 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-20 09:14:07 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Unable to match Friends.-.S10E16.-.The.One.With.Rachel's.Going.Away.Party.avi to a show in your database. Parser result: Friends - S10E16 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-20 09:14:07 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Transaction with 19 queries executed
2017-03-20 09:14:07 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2017-03-20 09:14:51 DEBUG    Thread-17 :: cur_commit = 78143873f776c0506c340c0eb6bab2f166952968, newest_commit = a0317f387e1df4fff138ca9f06abb6f40d7921d7, num_commits_behind = 4
2017-03-20 09:14:51 WARNING  Thread-17 :: Please update SickRage, unable to submit issue ticket to GitHub with an outdated version!
2017-03-20 09:15:08 INFO     Thread-17 :: Config backup in progress...
2017-03-20 09:15:13 INFO     Thread-17 :: Config backup successful, updating...
2017-03-20 09:15:30 DEBUG    Thread-17 :: cur_commit = 78143873f776c0506c340c0eb6bab2f166952968, newest_commit = a0317f387e1df4fff138ca9f06abb6f40d7921d7, num_commits_behind = 4
2017-03-20 09:15:30 INFO     Thread-17 :: Clearing out update folder /mnt/HDD/extensions/sickrage/sr-update before extracting
2017-03-20 09:15:31 INFO     Thread-17 :: Creating update folder /mnt/HDD/extensions/sickrage/sr-update before extracting
2017-03-20 09:15:31 INFO     Thread-17 :: Downloading update from http://github.com/SickRage/SickRage/tarball/master
2017-03-20 09:18:47 DEBUG    POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2017-03-20 09:18:47 INFO     POSTPROCESSOR :: Auto post processing task for /mnt/NAS/downloads was added to the queue
2017-03-20 09:18:51 INFO     POSTPROCESSOR-AUTO :: Beginning auto post processing task: /mnt/NAS/downloads
2017-03-20 09:18:51 DEBUG    POSTPROCESSOR-AUTO :: Processing in folder /mnt/NAS/downloads
2017-03-20 09:18:51 INFO     POSTPROCESSOR-AUTO :: Processing /mnt/NAS/downloads
2017-03-20 09:18:51 DEBUG    POSTPROCESSOR-AUTO :: Processing folder /mnt/NAS/downloads
2017-03-20 09:18:52 DEBUG    POSTPROCESSOR-AUTO :: Parsed american.crime.s03e02.720p.hdtv.hevc.x265.rmteam.mkv into american crime - S03E02 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2017-03-20 09:18:52 DEBUG    POSTPROCESSOR-AUTO :: You're trying to post process a video that's already been processed, skipping
2017-03-20 09:18:52 DEBUG    POSTPROCESSOR-AUTO :: Skipping already processed file: american.crime.s03e02.720p.hdtv.hevc.x265.rmteam.mkv
2017-03-20 09:18:52 DEBUG    POSTPROCESSOR-AUTO :: You're trying to post process a video that's already been processed, skipping
2017-03-20 09:18:52 DEBUG    POSTPROCESSOR-AUTO :: Skipping already processed file: The.Walking.Dead.S07E14.720p.HDTV.x265.ShAaNiG.mkv
2017-03-20 09:18:52 DEBUG    POSTPROCESSOR-AUTO :: Skipping already processed file: Last.Week.Tonight.with.John.Oliver.S04E06.720p.WEBRip.2CH.x265.HEVC-PSA.mkv
2017-03-20 09:18:52 DEBUG    POSTPROCESSOR-AUTO :: You're trying to post process a video that's already been processed, skipping
2017-03-20 09:18:52 DEBUG    POSTPROCESSOR-AUTO :: Skipping already processed file: feud.s01e03.720p.hdtv.hevc.x265.rmteam.mkv
2017-03-20 09:18:52 DEBUG    POSTPROCESSOR-AUTO :: You're trying to post process a video that's already been processed, skipping
2017-03-20 09:18:52 DEBUG    POSTPROCESSOR-AUTO :: Skipping already processed file: homeland.s06e09.proper.720p.hdtv.hevc.x265.rmteam.mkv
2017-03-20 09:18:52 DEBUG    POSTPROCESSOR-AUTO :: Processing folder /mnt/NAS/downloads/incomplete
2017-03-20 09:18:52 DEBUG    POSTPROCESSOR-AUTO :: /mnt/NAS/downloads/incomplete : No processable items found in folder
2017-03-20 09:18:52 INFO     POSTPROCESSOR-AUTO :: Successfully processed
2017-03-20 09:18:52 INFO     POSTPROCESSOR-AUTO :: Auto post processing task for /mnt/NAS/downloads completed
2017-03-20 09:20:07 INFO     Thread-17 :: Extracting file /mnt/HDD/extensions/sickrage/sr-update/sr-update.tar
2017-03-20 09:20:08 ERROR    Thread-17 :: [7814387] Error while trying to update: ascii : /mnt/HDD/extensions/sickrage/sr-update/SickRage-SickRage-a0317f3/gui/slick/images/network/stöð 2.png : error 92 : error 94 : ordinal not in range(128)
Traceback (most recent call last):
  File "/mnt/HDD/extensions/sickrage/sickbeard/versionChecker.py", line 816, in update
    tar.extractall(sr_update_dir)
  File "/usr/local/lib/python2.7/tarfile.py", line 2081, in extractall
    self.extract(tarinfo, path)
  File "/usr/local/lib/python2.7/tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/local/lib/python2.7/tarfile.py", line 2194, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/local/lib/python2.7/tarfile.py", line 2234, in makefile
    with bltn_open(targetpath, "wb") as target:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 92-93: ordinal not in range(128)
2017-03-20 09:20:08 DEBUG    Thread-17 :: Traceback: Traceback (most recent call last):
  File "/mnt/HDD/extensions/sickrage/sickbeard/versionChecker.py", line 816, in update
    tar.extractall(sr_update_dir)
  File "/usr/local/lib/python2.7/tarfile.py", line 2081, in extractall
    self.extract(tarinfo, path)
  File "/usr/local/lib/python2.7/tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/local/lib/python2.7/tarfile.py", line 2194, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/local/lib/python2.7/tarfile.py", line 2234, in makefile
    with bltn_open(targetpath, "wb") as target:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 92-93: ordinal not in range(128)


```

**Comment by SickRage2** [comment] 2017-03-20 13:25
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment] 2017-03-20 13:34
@miigotu do we have a function to parse the names as ascii? 
like `stöð 2.png` will become `stoo 2.png`?

**Comment by miigotu** [comment] 2017-03-20 13:50
It would have to use unidecode to go that route.
Atm we just use a hard coded replacement method
```python
    @property
    def network_logo_name(self):
        return self.network.replace('\u00C9', 'e').replace('\u00E9', 'e').lower()
```

However, I don't think that is the correct route.

The problem is in how the tar is opened, due to a bug in python: (this is an example with zipfile, which uses the same file-like code)
https://bugs.python.org/issue20329

**Comment by sharkykh** [comment] 2017-03-30 10:41
Fixed in https://github.com/SickRage/SickRage/commit/517ceeae22c52bdbf42823112061902138349af5

**Closed by sharkykh** 2017-03-30 10:41 UTC
